### ISSUE TITLE
Compilation error caused by implicit type conversion from String to int

### ISSUE THREAD

**Issue by tfuda** [forcedotcom/ApexUnit#19]
When I do a clean and compile operation, I'm getting a couple of compilation errors:

```
[INFO] Compiling 22 source files to C:\Users\tom\Development\Java\git\ApexUnit\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \Users\tom\Development\Java\git\ApexUnit\src\main\java\com\sforce\cd\apexUnit\client\connection\ConnectionHandler.java:[118,92] error: incompatible types: String cannot be converted to int
[ERROR] \Users\tom\Development\Java\git\ApexUnit\src\main\java\com\sforce\cd\apexUnit\client\connection\ConnectionHandler.java:[185,91] error: incompatible types: String cannot be converted to int
```

I believe the type of proxyPort property in CommandLineArguments.java should be changed from a String to an Integer, because the value for the proxy port argument passed to the ConnectionConfig.setProxy method is expected to be an int, and String cannot be implicitly converted to int.

**Comment by adarsh-ramakrishna-sfdc** [comment]
Thanks @tfuda 
I have recorded my review comments in the PR #20 
@vamshi-sfdc will take a look at it
