### ISSUE TITLE
Exclude test classes from code coverage computations

### ISSUE THREAD

**Issue by tfuda** [forcedotcom/ApexUnit#22]
Currently, if you use the -regex.for.selecting.source.classes.for.code.coverage.computation with a pattern of *, it will pull in ALL Apex classes within your default namespace and get the code coverage metrics for them. This includes Apex classes that are annotated with the "IsTest" annotation. The wildcard matching is implemented via a SOQL query against the ApexClass table with a LIKE clause, using the partner connection. This does not provide adequate metadata to identify which classes are annotated with "IsTest". As an enhancement, I think it should be possible to run a query via the Tooling API (you already establish a Tooling API connection to get the code coverage metrics anyway). The query might look something like this:

```
/services/data/v35.0/tooling/query?q=select+SymbolTable+FROM+ApexClass
```

Here's an example of one record returned by this query as viewed in Workbench: http://screencast.com/t/QFUnnSg5. You can see that it is possible to identify classes the have the IsTest annotation in this manner. Just something to think about as a possible future enhancement to make the regex options for selecting test classes and source classes more useful.

**Comment by pmedapuram** [comment]
@tfuda Thank you for reporting this issue.

I agree that computing code coverage for class that are annotated as *IsTest* is not required. We will get back to you on this feature.

**Comment by glang** [comment]
Hi @tfuda, I've been looking into this enhancement and what I found is that as long as a class contains a non-test method, which is a method that is not declared with the keyword 'testmethod', code coverage will be computed for those non-test method lines and only those lines. If there is a class with just test methods, no code coverage will be computed for it. When a class contains both test methods and non-test methods, code coverage will only be computed for the non-test method lines. Is this what you are looking for?

**Comment by tfuda** [comment]
Well, in our org, we usually annotate entire classes with @IsTest, but often classes annotated in this fashion will include methods that are NOT declared with the testMethod modifier. This is because our test classes often include utility methods that are use in creating scaffold data for the test methods within the class. I guess my hope was that we could somehow exclude the entire class from code coverage computations, otherwise these scaffolding methods may skew the overall test coverage numbers.

**Comment by glang** [comment]
Hi @tfuda , I see what you mean and this is something that others have brought up in the past as well. Unfortunately, according the Apex documentation, classes annotated with @isTest should only contain test methods. Here is a response from salesforce to a similar query as yours that you may find helpful: https://help.salesforce.com/apex/HTViewSolution?urlname=Why-is-a-Test-class-evaluated-as-part-of-the-Organization-s-Code-Coverage&language=en_US (on my computer the text is cut off a bit, but clicking the "print" button opens a page that is more readable). 

You can also request this as a feature on Ideas Exchange, which if enough people vote it up, it will be put on the roadmap: https://success.salesforce.com/ideaSearch
