### ISSUE TITLE
Is there a limitation of 200 test classes?

### ISSUE THREAD

**Issue by jineshkenandy** [forcedotcom/ApexUnit#41]
Hi,

I tried using ApexUnit for our app which has around 300+ test classes. The final report however shows 200 test classes executed. Is there any limitation on number of test classes that can be executed using ApexUnit?

Thanks,
Jinesh

**Comment by adarsh-ramakrishna-sfdc** [comment]
Hello @jineshkenandy 

There is no limit set on the # of test classes. Currently tests with 'default' namespace will be picked. If you have test classes belonging a different namespace, those will probably not be picked. 
Also, We have a enhancement request to support different namespaces(Issue #23  ) . Let me know if you have any questions

**Comment by adarshramakrishna** [comment]
@jineshkenandy  Please let me know if you have any questions. Closing this question for now. Thanks
